Update packer.yaml

diff --git a/.github/workflows/packer.yaml b/.github/workflows/packer.yaml
--- a/.github/workflows/packer.yaml
+++ b/.github/workflows/packer.yaml
@@ -60,10 +60,11 @@ jobs:
               ${{ inputs.dispatches_repo }} \
               -d '{"event_type":"${{ inputs.dispatches_event_type }}","client_payload":{"unit":false,"integration":true}}'
           
-            if [ $? != 0 ]
-            then
-                 echo "Error in githubactions dispatches trigger event"
-                 exit 1
-            fi
+            echo $?
+#            if [ $? != 0 ]
+#            then
+#                 echo "Error in githubactions dispatches trigger event"
+#                 exit 1
+#            fi
 #https://developer.hashicorp.com/packer/docs/commands/init
 #curl -i https://api.github.com/users/octocat     
